---
development:
  cloud_name: dxffyb2vl
  api_key: '231412626971825'
  api_secret: IMpKOCCZjGEuaQgtTBe_3hn214U
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dxffyb2vl
  api_key: '231412626971825'
  api_secret: IMpKOCCZjGEuaQgtTBe_3hn214U
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dxffyb2vl
  api_key: '231412626971825'
  api_secret: IMpKOCCZjGEuaQgtTBe_3hn214U
  enhance_image_tag: true
  static_image_support: false
