default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: imgtomap_development

test:
  <<: *default
  database: imgtomap_test

production:
  <<: *default
  database: imgtomap_production
  username: imgtomap
  password: <%= ENV['IMGTOMAP_DATABASE_PASSWORD'] %>
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>